sonar.organization=edgefirstai
sonar.projectKey=EdgeFirstAI_fusion
sonar.projectName=EdgeFirst Fusion
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

# Disable SonarCloud's internal Clippy - we run it separately in CI
sonar.rust.clippy.enabled=false
